// 卷次与篇目以共产党员网公开的《毛泽东选集》1-4 卷目录及文本为校验入口，
// 版本信息采用人民出版社 1991 年第 2 版。仅收录适合卡片展示的短句摘录。
const VOLUME_URLS = {
  1: 'https://www.12371.cn/special/mzdxj/dyj/',
  2: 'https://www.12371.cn/special/mzdxj/dej/',
  3: 'https://www.12371.cn/special/mzdxj/d3j/',
  4: 'https://www.12371.cn/special/mzdxj/d4j/',
};

const VERIFICATION_URLS = {
  1: 'http://theory.people.com.cn/n/2014/0603/c385524-25097029.html',
  5: 'http://dangshi.people.com.cn/n/2013/1205/c85037-23752088-2.html',
  11: 'http://dangshi.people.com.cn/n1/2021/0118/c85037-32002486.html',
  13: 'http://dangshi.people.com.cn/n1/2017/0913/c85037-29532496.html',
  17: 'http://dangshi.people.com.cn/n1/2016/0612/c85037-28425916.html',
  18: 'http://dangshi.people.com.cn/n/2013/1226/c85037-23952322.html',
  26: 'http://theory.people.com.cn/n1/2021/0721/c40531-32165046.html',
  43: 'http://dangshi.people.com.cn/n1/2018/0302/c85037-29843461.html',
  46: 'http://dangshi.people.com.cn/n/2013/0228/c85037-20626581-5.html',
  47: 'http://dangshi.people.com.cn/n1/2019/1122/c85037-31468434.html',
  49: 'http://dangshi.people.com.cn/n1/2015/0722/c85037-27342801.html',
  52: 'http://dangshi.people.com.cn/n1/2021/0118/c85037-32002486.html',
  53: 'http://dangshi.people.com.cn/n/2014/0314/c85037-24638551.html',
  61: 'http://theory.people.com.cn/n1/2019/0428/c40531-31054665.html',
  66: 'http://dangshi.people.com.cn/n/2013/0708/c85037-22112745-2.html',
  81: 'http://dangshi.people.com.cn/n1/2021/1126/c436975-32292441.html',
  97: 'http://dangshi.people.com.cn/n1/2016/0613/c85037-28428915-5.html',
  99: 'http://dangshi.people.com.cn/n/2013/0712/c85037-22173097.html',
  100: 'http://dangshi.people.com.cn/n/2013/0712/c85037-22173097.html',
};

const SOURCES = {
  CLASS_ANALYSIS: [1, '中国社会各阶级的分析'],
  HUNAN_REPORT: [1, '湖南农民运动考察报告'],
  JINGGANG: [1, '井冈山的斗争'],
  SPARKS: [1, '星星之火，可以燎原'],
  AGAINST_DOGMATISM: [1, '反对本本主义'],
  CONCERN_MASSES: [1, '关心群众生活，注意工作方法'],
  STRATEGIC_PROBLEMS: [1, '中国革命战争的战略问题'],
  PRACTICE: [1, '实践论'],
  CONTRADICTION: [1, '矛盾论'],
  PROTRACTED_WAR: [2, '论持久战'],
  BETHUNE: [2, '纪念白求恩'],
  WAR_AND_STRATEGY: [2, '战争和战略问题'],
  INDEPENDENCE: [2, '统一战线中的独立自主问题'],
  UNITED_FRONT_STRATEGY: [2, '目前抗日统一战线中的策略问题'],
  ON_NEW_DEMOCRACY: [2, '新民主主义论'],
  RURAL_SURVEY: [3, '〈农村调查〉的序言和跋'],
  REFORM_STUDY: [3, '改造我们的学习'],
  RECTIFY_STYLE: [3, '整顿党的作风'],
  AGAINST_PARTY_EIGHT: [3, '反对党八股'],
  YANAN_ART: [3, '在延安文艺座谈会上的讲话'],
  LEADERSHIP_METHODS: [3, '关于领导方法的若干问题'],
  SERVE_PEOPLE: [3, '为人民服务'],
  ON_COALITION: [3, '论联合政府'],
  YUGONG: [3, '愚公移山'],
  ORGANIZE: [3, '组织起来'],
  STRONG_INTERVIEW: [4, '和美国记者安娜·路易斯·斯特朗的谈话'],
  CURRENT_TASKS: [4, '目前形势和我们的任务'],
  SITUATION_REPORT: [4, '关于情况的通报'],
  JINSUI_TALK: [4, '在晋绥干部会议上的讲话'],
  PRESS_TALK: [4, '对晋绥日报编辑人员的谈话'],
  SECOND_PLENUM: [4, '在中国共产党第七届中央委员会第二次全体会议上的报告'],
  COMMITTEE_METHODS: [4, '党委会的工作方法'],
  PEOPLE_DEMOCRATIC: [4, '论人民民主专政'],
};

const RAW_QUOTES = [
  [1, '没有调查，没有发言权。', 'AGAINST_DOGMATISM'],
  [2, '从群众中来，到群众中去。', 'LEADERSHIP_METHODS'],
  [3, '我们这个队伍完全是为着解放人民的，是彻底地为人民的利益工作的。', 'SERVE_PEOPLE'],
  [4, '星星之火，可以燎原。', 'SPARKS'],
  [5, '一切反动派都是纸老虎。', 'STRONG_INTERVIEW'],
  [6, '读书是学习，使用也是学习，而且是更重要的学习。', 'STRATEGIC_PROBLEMS'],
  [7, '实践、认识、再实践、再认识，这种形式，循环往复以至无穷。', 'PRACTICE'],
  [8, '矛盾即是运动，即是事物，即是过程，也即是思想。', 'CONTRADICTION'],
  [9, '事物矛盾的法则，即对立统一的法则，是自然和社会的根本法则，因而也是思维的根本法则。', 'CONTRADICTION'],
  [10, '战争的目的不是别的，就是保存自己，消灭敌人。', 'PROTRACTED_WAR'],
  [11, '兵民是胜利之本。', 'PROTRACTED_WAR'],
  [12, '抗日战争是持久战，最后胜利是中国的。', 'PROTRACTED_WAR'],
  [13, '为人民利益而死，就比泰山还重；替剥削人民和压迫人民的人去死，就比鸿毛还轻。', 'SERVE_PEOPLE'],
  [14, '人总是要死的，但死的意义有不同。', 'SERVE_PEOPLE'],
  [15, '因为我们是为人民服务的，所以，我们如果有缺点，就不怕别人批评指出。', 'SERVE_PEOPLE'],
  [16, '毫不利己专门利人的精神，表现在他对工作的极端的负责任，对同志对人民的极端的热忱。', 'BETHUNE'],
  [17, '一个人能力有大小，但只要有这点精神，就是一个高尚的人，一个纯粹的人，一个有道德的人，一个脱离了低级趣味的人，一个有益于人民的人。', 'BETHUNE'],
  [18, '下定决心，不怕牺牲，排除万难，去争取胜利。', 'YUGONG'],
  [19, '现在也有两座压在中国人民头上的大山，一座叫做帝国主义，一座叫做封建主义。', 'YUGONG'],
  [20, '中国革命斗争的胜利要靠中国同志了解中国情况。', 'AGAINST_DOGMATISM'],
  [21, '马克思主义的“本本”是要学习的，但是必须同我国的实际情况相结合。', 'AGAINST_DOGMATISM'],
  [22, '调查就像“十月怀胎”，解决问题就像“一朝分娩”。', 'AGAINST_DOGMATISM'],
  [23, '真正的铜墙铁壁是什么？是群众，是千百万真心实意地拥护革命的群众。', 'CONCERN_MASSES'],
  [24, '没有贫农，便没有革命。', 'HUNAN_REPORT'],
  [25, '革命的中心任务和最高形式是武装夺取政权，是战争解决问题。', 'WAR_AND_STRATEGY'],
  [26, '谁是我们的敌人？谁是我们的朋友？这个问题是革命的首要问题。', 'CLASS_ANALYSIS'],
  [27, '敌进我退，敌驻我扰，敌疲我打，敌退我追。', 'JINGGANG'],
  [28, '从战争学习战争，这是我们的主要方法。', 'STRATEGIC_PROBLEMS'],
  [29, '决定战争胜败的是人民，而不是一两件新式武器。', 'STRONG_INTERVIEW'],
  [30, '统一战线中的独立自主这个原则的说明、实践和坚持，是把抗日民族革命战争引向胜利之途的中心一环。', 'INDEPENDENCE'],
  [31, '新民主主义的政治、新民主主义的经济和新民主主义的文化相结合，这就是新民主主义共和国。', 'ON_NEW_DEMOCRACY'],
  [32, '我们看事情必须要看它的实质，而把它的现象只看作入门的向导。', 'SPARKS'],
  [33, '捉住了这个主要矛盾，一切问题就迎刃而解了。', 'CONTRADICTION'],
  [34, '我们的任务是过河，但是没有桥或没有船就不能过。', 'COMMITTEE_METHODS'],
  [35, '世上决没有无缘无故的爱，也没有无缘无故的恨。', 'YANAN_ART'],
  [36, '为什么人的问题，是一个根本的问题，原则的问题。', 'YANAN_ART'],
  [37, '“实事”就是客观存在着的一切事物，“是”就是客观事物的内部联系，即规律性，“求”就是我们去研究。', 'REFORM_STUDY'],
  [38, '马克思列宁主义的理论和中国革命的实际运动结合起来，是为着解决中国革命的理论问题和策略问题而去从它找立场，找观点，找方法的。', 'REFORM_STUDY'],
  [39, '这种态度，就是实事求是的态度。', 'REFORM_STUDY'],
  [40, '墙上芦苇，头重脚轻根底浅；山间竹笋，嘴尖皮厚腹中空。', 'REFORM_STUDY'],
  [41, '这种反科学的反马克思列宁主义的主观主义的方法，是共产党的大敌，是工人阶级的大敌，是人民的大敌，是民族的大敌，是党性不纯的一种表现。', 'REFORM_STUDY'],
  [42, '只有打倒了主观主义，马克思列宁主义的真理才会抬头，党性才会巩固，革命才会胜利。', 'RECTIFY_STYLE'],
  [43, '群众是真正的英雄，而我们自己则往往是幼稚可笑的。', 'RURAL_SURVEY'],
  [44, '反对主观主义以整顿学风，反对宗派主义以整顿党风，反对党八股以整顿文风。', 'RECTIFY_STYLE'],
  [45, '党八股是藏垢纳污的东西，是主观主义和宗派主义的一种表现形式。', 'AGAINST_PARTY_EIGHT'],
  [46, '我们不但善于破坏一个旧世界，我们还将善于建设一个新世界。', 'SECOND_PLENUM'],
  [47, '夺取全国胜利，这只是万里长征走完了第一步。', 'SECOND_PLENUM'],
  [48, '中国的命运一经操在人民自己的手里，中国就将如太阳升起在东方那样。', 'PEOPLE_DEMOCRATIC'],
  [49, '人民，只有人民，才是创造世界历史的动力。', 'ON_COALITION'],
  [50, '没有中国共产党的努力，没有中国共产党人做中国人民的中流砥柱，中国的独立和解放是不可能的。', 'ON_COALITION'],
  [51, '共产党人的一切言论行动，必须以合乎最广大人民群众的最大利益，为最广大人民群众所拥护为最高标准。', 'ON_COALITION'],
  [52, '武器是战争的重要的因素，但不是决定的因素，决定的因素是人不是物。', 'PROTRACTED_WAR'],
  [53, '战争的伟力之最深厚的根源，存在于民众之中。', 'PROTRACTED_WAR'],
  [54, '主动性、灵活性、计划性，是战争指导的重要问题。', 'PROTRACTED_WAR'],
  [55, '保存自己消灭敌人这个战争的目的，就是战争的本质。', 'PROTRACTED_WAR'],
  [56, '内因是变化的根据，外因是变化的条件，外因通过内因而起作用。', 'CONTRADICTION'],
  [57, '矛盾的普遍性和矛盾的特殊性的关系，就是矛盾的共性和个性的关系。', 'CONTRADICTION'],
  [58, '任何过程如果有多数矛盾存在的话，其中必定有一种是主要的。', 'CONTRADICTION'],
  [59, '感觉到了的东西，我们不能立刻理解它，只有理解了的东西才更深刻地感觉它。', 'PRACTICE'],
  [60, '认识从实践始，经过实践得到了理论的认识，还须再回到实践去。', 'PRACTICE'],
  [61, '真理的标准只能是社会的实践。', 'PRACTICE'],
  [62, '无产阶级和革命人民改造世界的斗争，包括实现下述的任务：改造客观世界，也改造自己的主观世界。', 'PRACTICE'],
  [63, '马克思主义者认为，只有人们的社会实践，才是人们对于外界认识的真理性的标准。', 'PRACTICE'],
  [64, '通过实践而发现真理，又通过实践而证实真理和发展真理。', 'PRACTICE'],
  [65, '认识的真正任务在于经过感觉而到达于思维。', 'PRACTICE'],
  [66, '凡属正确的领导，必须是从群众中来，到群众中去。', 'LEADERSHIP_METHODS'],
  [67, '将群众的意见集中起来，又到群众中去作宣传解释，化为群众的意见，使群众坚持下去。', 'LEADERSHIP_METHODS'],
  [68, '从群众中集中起来又到群众中坚持下去，以形成正确的领导意见。', 'LEADERSHIP_METHODS'],
  [69, '党委书记要善于当“班长”。', 'COMMITTEE_METHODS'],
  [70, '不懂得和不了解的东西要问下级，不要轻易表示赞成或反对。', 'COMMITTEE_METHODS'],
  [71, '要“不耻下问”，善于倾听下面干部的意见。', 'COMMITTEE_METHODS'],
  [72, '什么叫问题？问题就是事物的矛盾。', 'COMMITTEE_METHODS'],
  [73, '要把问题摆到桌面上来。', 'COMMITTEE_METHODS'],
  [74, '党委各委员之间要把彼此知道的情况互相通知、互相交流。', 'COMMITTEE_METHODS'],
  [75, '善于团结和自己意见不同的同志一道工作。', 'COMMITTEE_METHODS'],
  [76, '要团结一切可以团结的人，包括反对过自己反对错了的人。', 'COMMITTEE_METHODS'],
  [77, '我们共产党人好比种子，人民好比土地。我们到了一个地方，就要同那里的人民结合起来，在人民中间生根、开花。', 'ON_COALITION'],
  [78, '人民靠我们去组织。中国的反动分子，靠我们组织起人民去把他打倒。', 'PEOPLE_DEMOCRATIC'],
  [79, '革命不是请客吃饭，不是做文章，不是绘画绣花，不能那样雅致，那样从容不迫。', 'HUNAN_REPORT'],
  [80, '矫枉必须过正，不过正不能矫枉。', 'HUNAN_REPORT'],
  [81, '革命是暴动，是一个阶级推翻一个阶级的暴烈的行动。', 'HUNAN_REPORT'],
  [82, '中国的红军是一个执行革命的政治任务的武装集团。', 'JINGGANG'],
  [83, '红军的打仗，不是单纯地为了打仗而打仗，而是为了宣传群众、组织群众、武装群众，并帮助群众建设革命政权才去打仗的。', 'JINGGANG'],
  [84, '组织革命战争，改良群众生活，这是我们的两大任务。', 'CONCERN_MASSES'],
  [85, '中国革命的主要形式，只能是武装的革命反对武装的反革命。', 'WAR_AND_STRATEGY'],
  [86, '每个共产党员都应懂得这个真理：“枪杆子里面出政权”。', 'WAR_AND_STRATEGY'],
  [87, '统一战线中的又联合又斗争，是相辅相成的。', 'UNITED_FRONT_STRATEGY'],
  [88, '中国革命的历史特点是分为民主主义和社会主义两个步骤。', 'ON_NEW_DEMOCRACY'],
  [89, '新民主主义的文化是民族的、科学的、大众的文化。', 'ON_NEW_DEMOCRACY'],
  [90, '我们的文学艺术都是为人民大众的，首先是为工农兵的，为工农兵而创作，为工农兵所利用的。', 'YANAN_ART'],
  [91, '人民生活中本来存在着文学艺术原料的矿藏，这是自然形态的东西，是粗糙的东西，但也是最生动、最丰富、最基本的东西。', 'YANAN_ART'],
  [92, '全党办报，群众办报。', 'PRESS_TALK'],
  [93, '报纸的作用和力量，就在它能使党的纲领路线，方针政策，工作任务和工作方法，最迅速最广泛地同群众见面。', 'PRESS_TALK'],
  [94, '办报人员也要向群众学习，戒骄戒躁。', 'PRESS_TALK'],
  [95, '自己动手，丰衣足食。', 'ORGANIZE'],
  [96, '我们必须组织起来。', 'ORGANIZE'],
  [97, '政策和策略是党的生命，各级领导同志务必充分注意，万万不可粗心大意。', 'SITUATION_REPORT'],
  [98, '严重的问题是教育农民。', 'PEOPLE_DEMOCRATIC'],
  [99, '务必使同志们继续地保持谦虚、谨慎、不骄、不躁的作风。', 'SECOND_PLENUM'],
  [100, '务必使同志们继续地保持艰苦奋斗的作风。', 'SECOND_PLENUM'],
];

function buildQuote([id, content, sourceKey]) {
  const [volume, title] = SOURCES[sourceKey];
  const sourceTitle = `《${title}》`;
  const verificationUrl = VERIFICATION_URLS[id] || null;
  return {
    id,
    content,
    volume,
    sourceTitle,
    source: `第${'一二三四'[volume - 1]}卷 · ${sourceTitle}`,
    sourceUrl: VOLUME_URLS[volume],
    sourcePublisher: '中共中央组织部共产党员网',
    sourceEdition: '《毛泽东选集》第2版，人民出版社，1991年',
    verificationUrl,
    verificationPublisher: verificationUrl ? '人民网 / 中国共产党新闻网' : null,
    verificationStatus: verificationUrl ? 'verified' : 'source-mapped',
    verifiedAt: verificationUrl ? '2026-07-20' : null,
    quoteType: 'short_excerpt',
    charCount: content.length,
    normalization: {
      script: '简体中文',
      punctuationPolicy: '按公开权威文本保留',
      modified: false,
    },
    author: '毛泽东',
  };
}

const QUOTES = RAW_QUOTES.map(buildQuote);

function getAllQuotes() {
  return QUOTES.map((quote) => ({ ...quote }));
}

function getQuoteById(id) {
  const quote = QUOTES.find((item) => item.id === Number(id));
  return quote ? { ...quote } : null;
}

function getQuotesByIds(ids) {
  const idSet = new Set(ids.map(Number));
  return QUOTES.filter((quote) => idSet.has(quote.id)).map((quote) => ({ ...quote }));
}

module.exports = {
  getAllQuotes,
  getQuoteById,
  getQuotesByIds,
  QUOTE_COUNT: QUOTES.length,
};
